<?php
###############################################################################
#                  Narga's Guestbook v.1.0 for Xoops 2.x                      #
#             Writen by  Nguyen Dinh Quan (webmaster@narga.tk)                #
#      .: Narga Vault :-: The Land Of Dreams :.(http://www.narga.tk)          #
#   ------------------------------------------------------------------------- #
#                                                                             #
#   ------------------------------------------------------------------------- #
#   This program is free software; you can redistribute it and/or modify      #
#   it under the terms of the GNU General Public License as published by      #
#   the Free Software Foundation; either version 2 of the License, or         #
#   (at your option) any later version.                                       #
#                                                                             #
#   This program is distributed in the hope that it will be useful,           #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of            #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
#   GNU General Public License for more details.                              #
#                                                                             #
#   You should have received a copy of the GNU General Public License         #
#   along with this program; if not, write to the Free Software               #
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA  #
#   ------------------------------------------------------------------------  #
###############################################################################
// $Id: xoops_version.php,v 1.2 Date: 22/06/2003, Author: Nguyen Dinh Quan Exp $

$modversion['name'] = _MI_NAR_MODULE_NAME;
$modversion['version'] = 1.4;
$modversion['description'] = _MI_NAR_MODULE_DESC;
$modversion['credits'] = "Developped by webmaster@narga.tk from http://www.narga.tk";
$modversion['author'] = "Nguyen Dinh Quan";
$modversion['help'] = "top.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 1;
$modversion['image'] = "./images/guestbook_logo.gif";
$modversion['dirname'] = "myguestbook";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
// All tables should not have any prefix!
$modversion['tables'][0] = "myguestbook";

//Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";
// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = "include/search.inc.php";
$modversion['search']['func'] = "myguestbook_search";

// Menu
$modversion['hasMain'] = 1;
// Templates
$modversion['templates'][1]['file']	= 'guestbook_index.html';
$modversion['templates'][1]['description'] = 'Guestbook Main Screen';
$modversion['templates'][2]['file']	= 'myguestbook_sign.html';
$modversion['templates'][2]['description'] = 'Shows Guestbook Sign Form';
$modversion['templates'][3]['file']	= 'guestbook_messages.html';
$modversion['templates'][3]['description'] = 'Guestbook Messages';
$modversion['templates'][4]['file']	= 'view_guestbook_messages.html';
$modversion['templates'][4]['description'] = 'View Guestbook Messages';
// Config Settings (only for modules that need config settings generated automatically)

// name of config option for accessing its specified value. i.e. $xoopsModuleConfig['storyhome']
$modversion['config'][1]['name'] = 'num_messages';

// title of this config option displayed in config settings form
$modversion['config'][1]['title'] = '_MI_NAR_NUMITEM';

// description of this config option displayed under title
$modversion['config'][1]['description'] = '_MI_NAR_NUMITEMDES';

// form element type used in config form for this option. can be one of either textbox, textarea, select, select_multi, yesno, group, group_multi
$modversion['config'][1]['formtype'] = 'textbox';

// value type of this config option. can be one of either int, text, float, array, or other
// form type of group_multi, select_multi must always be value type of array
$modversion['config'][1]['valuetype'] = 'int';

// the default value for this option
// ignore it if no default
// 'yesno' formtype must be either 0(no) or 1(yes)
$modversion['config'][1]['default'] = 5;

$modversion['config'][2]['name'] = 'order';
$modversion['config'][2]['title'] = '_MI_NAR_ORDER';
$modversion['config'][2]['description'] = '_MI_NAR_ORDERDES';
$modversion['config'][2]['formtype'] = 'select';
$modversion['config'][2]['valuetype'] = 'text';
$modversion['config'][2]['default'] = desc;
$modversion['config'][2]['options']	= array('_MI_NAR_ASC' => 'asc', '_MI_NAR_DESC' => 'desc');

$modversion['config'][3]['name'] = 'allowicons';
$modversion['config'][3]['title'] = '_MI_NAR_ICONS';
$modversion['config'][3]['description'] = '_MI_NAR_ICONSDES';
$modversion['config'][3]['formtype'] = 'yesno';
$modversion['config'][3]['valuetype'] = 'int';
$modversion['config'][3]['default'] = 1;
//$modversion['config'][3]['options']	= array('_MI_NAR_ICQ' => 'allow_icq', '_MI_NAR_MSN' => 'allow_msn', '_MI_NAR_AIM' => 'allow_aim', '_MI_NAR_YIM' => 'allow_yim', '_MI_NAR_GENDER' => 'allow_gender', '_MI_NAR_EMAIL' => 'allow_email');

$modversion['config'][4]['name'] = 'sendmail';
$modversion['config'][4]['title'] = '_MI_NAR_SENDMAIL';
$modversion['config'][4]['description'] = '_MI_NAR_SENDMAILDES';
$modversion['config'][4]['formtype'] = 'yesno';
$modversion['config'][4]['valuetype'] = 'int';
$modversion['config'][4]['default'] = 0;

$modversion['config'][5]['name'] = 'date';
$modversion['config'][5]['title'] = '_MI_NAR_TIME';
$modversion['config'][5]['description'] = '_MI_NAR_TIMEDES';
$modversion['config'][5]['formtype'] = 'select';
$modversion['config'][5]['valuetype'] = 'text';
$modversion['config'][5]['default'] = desc;
$modversion['config'][5]['options']	= array('_MI_NAR_TIME1' => '0', '_MI_NAR_TIME2' => '1');
//Notification option
?>